### ISSUE TITLE
Class 'Omeka_plugin_AbstractPlugin' not found

### ISSUE THREAD

**Issue by ebrassel** [UCSCLibrary/AdminImages#12]
Hi, I think there is a typo in AdminImagesPlugin.php (line 15) that's causing a 500 error when I try to install AdminImages:

` PHP Fatal error:  Uncaught Error: Class 'Omeka_plugin_AbstractPlugin' not found in /htdocs/exhibits/plugins/AdminImages/AdminImagesPlugin.php:15`

Changing it to 'Omeka_Plugin_AbstractPlugin' seems to fix the error.

Thanks!

**Comment by csidirop** [comment]
Have the same issue. Getting following stack trace:

```
Fatal error: Uncaught Error: Class "Omeka_plugin_AbstractPlugin" not found in /var/www/html/omekatest/plugins/AdminImages/AdminImagesPlugin.php:15 
Stack trace: 
#0 /var/www/html/omekatest/application/libraries/Omeka/Plugin/Loader.php(285): require_once() 
#1 /var/www/html/omekatest/application/libraries/Omeka/Plugin/Loader.php(243): Omeka_Plugin_Loader->hasPluginBootstrap() 
#2 /var/www/html/omekatest/application/libraries/Omeka/Plugin/Loader.php(148): Omeka_Plugin_Loader->_canLoad() 
#3 /var/www/html/omekatest/application/libraries/Omeka/Plugin/Loader.php(90): Omeka_Plugin_Loader->load() 
#4 /var/www/html/omekatest/application/controllers/PluginsController.php(274): Omeka_Plugin_Loader->loadPlugins() 
#5 /var/www/html/omekatest/application/libraries/Zend/Controller/Action.php(516): PluginsController->browseAction() 
#6 /var/www/html/omekatest/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch() 
#7 /var/www/html/omekatest/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch() 
#8 /var/www/html/omekatest/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch() 
#9 /var/www/html/omekatest/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run() 
#10 /var/www/html/omekatest/application/libraries/Omeka/Application.php(73): Zend_Application->run() 
#11 /var/www/html/omekatest/admin/index.php(28): Omeka_Application->run() 
#12 {main} thrown in /var/www/html/omekatest/plugins/AdminImages/AdminImagesPlugin.php on line 15
```

After setting up some other plugins I re unzipped it and the error was gone and the plugin page load correctly. Had this behavior both times setting a new omeka classic instance up.
